name: HNPlayerSignature
version: '${version}'
main: com.heynight0712.hnplayersignature.HNPlayerSignature
api-version: '1.20'
softdepend: [Vault]
loadbefore:
  - Vault

####################################################
commands:
  hnplayersignature:
    aliases: [sign]
    description: "簽名物品系統"
    usage: /hnplayersignature [subcommand]

####################################################