name: HNItem
version: '${version}'
main: com.heynight0712.hnitem.HNItem
api-version: '1.20'
softdepend: [Vault]
loadbefore:
  - Vault

####################################################
commands:
  sign:
    aliases: [sign]
    description: "簽名物品系統"
    usage: /sign [subcommand]

  withdraw:
    aliases: [withdraw]
    description: "貨幣實體化"
    usage: /withdraw <幣值> <數量>

####################################################